### ISSUE TITLE
Logical Operators like && or || not working in if statement

### ISSUE THREAD

**Issue by Wonderlight800** [RyanZim/EJS-Lint#101]
While using the || logical operator ejs is always throwing the following error:

SyntaxError: Unexpected token '||' in D:\data\Documents\myPage\views\test.ejs while compiling ejs

If the above error is not helpful, you may want to try EJS-Lint:
https://github.com/RyanZim/EJS-Lint
Or, if you meant to create an async function, pass `async: true` as an option.
    at new Function (<anonymous>)
    at Template.compile (D:\data\Documents\myPage\node_modules\ejs\lib\ejs.js:662:12)
    at Object.compile (D:\data\Documents\myPage\node_modules\ejs\lib\ejs.js:396:16)
    at handleCache (D:\data\Documents\myPage\node_modules\ejs\lib\ejs.js:233:18)
    at tryHandleCache (D:\data\Documents\myPage\node_modules\ejs\lib\ejs.js:272:16)
    at View.exports.renderFile [as engine] (D:\data\Documents\myPage\node_modules\ejs\lib\ejs.js:489:10)
    at View.render (D:\data\Documents\myPage\node_modules\express\lib\view.js:135:8)
    at tryRender (D:\data\Documents\myPage\node_modules\express\lib\application.js:640:10)
    at Function.render (D:\data\Documents\myPage\node_modules\express\lib\application.js:592:3)
    at ServerResponse.render (D:\data\Documents\myPage\node_modules\express\lib\response.js:1012:7)
    at D:\data\Documents\myPage\routes\de.js:107:9
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by RyanZim** [comment]
Not sure why you'd be getting this error, your code looks fine. Maybe try to to make a reduced test case?
