### ISSUE TITLE
I have a Dashboard that uses this dependency and its not working 

### ISSUE THREAD

**Issue by TrissieTheHusky** [RyanZim/EJS-Lint#51]
### The Code is below 
The Error Code I get is :

```

SyntaxError: Unexpected token / in /app/views/index.ejs while compiling ejs

If the above error is not helpful, you may want to try EJS-Lint:
https://github.com/RyanZim/EJS-Lint
Or, if you meant to create an async function, pass `async: true` as an option.
    at new Function (<anonymous>)
    at Template.compile (/rbd/pnpm-volume/43626e5b-4de6-4046-89b5-052d64645ce1/node_modules/.registry.npmjs.org/ejs/3.0.1/node_modules/ejs/lib/ejs.js:626:12)
    at Object.compile (/rbd/pnpm-volume/43626e5b-4de6-4046-89b5-052d64645ce1/node_modules/.registry.npmjs.org/ejs/3.0.1/node_modules/ejs/lib/ejs.js:366:16)
    at handleCache (/rbd/pnpm-volume/43626e5b-4de6-4046-89b5-052d64645ce1/node_modules/.registry.npmjs.org/ejs/3.0.1/node_modules/ejs/lib/ejs.js:215:18)
    at tryHandleCache (/rbd/pnpm-volume/43626e5b-4de6-4046-89b5-052d64645ce1/node_modules/.registry.npmjs.org/ejs/3.0.1/node_modules/ejs/lib/ejs.js:254:16)
    at View.exports.renderFile [as engine] (/rbd/pnpm-volume/43626e5b-4de6-4046-89b5-052d64645ce1/node_modules/.registry.npmjs.org/ejs/3.0.1/node_modules/ejs/lib/ejs.js:459:10)
    at View.render (/rbd/pnpm-volume/43626e5b-4de6-4046-89b5-052d64645ce1/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/view.js:135:8)
    at tryRender (/rbd/pnpm-volume/43626e5b-4de6-4046-89b5-052d64645ce1/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/application.js:640:10)
    at Function.render (/rbd/pnpm-volume/43626e5b-4de6-4046-89b5-052d64645ce1/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/rbd/pnpm-volume/43626e5b-4de6-4046-89b5-052d64645ce1/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/response.js:1012:7)
```
I've tried everything the source code for my dashboard is there the link to my dashboard is [South Dashboard](https://south-bot.glitch.me)
If you could help that would be awesome

The HTML CODE that the error is originating from:

```
<!DOCTYPE html>
<html lang="en">
<%- include('partials/header.ejs') %>
<body>
  <%- include('partials/navbar.ejs') %>
  <div class="page-content">
    <% if (!user || !guilds) { %>
      <center><h1>Welcome</h1>
      <p>To get started, login by clicking <em>Login</em> on the navbar, then go to the servers page and choose a server to manage.</p></center>
    <% } else { %>
      <div class="userinfo">
        <h1>
          Welcome <%= user.username %>#<%= user.discriminator %>
        </h1>

        <p>Choose a server to begin</p><br><br>
      </div>
      <%- include('partials/servers.ejs') %><% } %>    
    </div>
</body>
</center>
<center>
  <div>
    <a href="https://discordapp.com/oauth2/authorize?client_id=627949687965745182&permissions=8&scope=bot" target="_blank">Invite Me</a>
  </div>
<p>Paid Premium Plan's Coming Soon</p>
<footer>Made By Trissie The Husky#0001 OwO</footer>
</html>
<% include ./partials/footer %>
</center>
```

**Comment by RyanZim** [comment]
What version of EJS are you using?
