### ISSUE TITLE
Issues with ejs lint syntax in comments

### ISSUE THREAD

**Issue by IlijazM** [RyanZim/EJS-Lint#99]
I have a ejs file that contains this line:

`<%# <jhipster-dependencies.version><%= JHIPSTER_DEPENDENCIES_VERSION %></jhipster-dependencies.version> %>`

I've used the ejs syntax to comment an ejs syntax. The ejs renderer however doesn't like that and throws:

`ERROR! Could not find matching close tag for "<%#".
Error: Could not find matching close tag for "<%#".
    at /home/imehmedovic/git/generator-jhipster/node_modules/ejs/lib/ejs.js:740:19
    at Array.forEach (<anonymous>)
    at Template.generateSource (/home/imehmedovic/git/generator-jhipster/node_modules/ejs/lib/ejs.js:730:15)
    at Template.compile (/home/imehmedovic/git/generator-jhipster/node_modules/ejs/lib/ejs.js:585:12)
    at Object.compile (/home/imehmedovic/git/generator-jhipster/node_modules/ejs/lib/ejs.js:396:16)
    at handleCache (/home/imehmedovic/git/generator-jhipster/node_modules/ejs/lib/ejs.js:233:18)
    at /home/imehmedovic/git/generator-jhipster/node_modules/ejs/lib/ejs.js:258:20
    at new Promise (<anonymous>)
    at tryHandleCache (/home/imehmedovic/git/generator-jhipster/node_modules/ejs/lib/ejs.js:256:14)
`
The ejs renderer doesn't include more and helpful information unfortunately.
But when I run ejs lint on that exact file the code seams to be just fine:

**Steps to reproduce**

`npm i ejs
echo "<%#<%=''%>%>">foo.ejs
echo "var ejs=require('ejs'),fs=require('fs');ejs.render(fs.readFileSync('foo.ejs','utf-8'))">index.js
ejslint foo.ejs
node .`

**Comment by RyanZim** [comment]
Yeah, I'm actually personally puzzled as to why EJS itself doesn't like that line; at first glance, it looks fine to me. Perhaps open an issue on the main EJS repo about this? Maybe @mde can see the problem.
